In [12]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import numpy as np

In [2]:
corpus = [
    'you know I want your love',
    'I like you',
    'what should I do ',    
]

In [14]:
cv = CountVectorizer()
tfidfv = TfidfVectorizer()

In [17]:
print(cv.fit(corpus))
print(cv.fit_transform(corpus).toarray())
# DTM(Document Term Matrix)

CountVectorizer()
[[0 1 0 1 0 1 0 1 1]
 [0 0 1 0 0 0 0 1 0]
 [1 0 0 0 1 0 1 0 0]]


In [19]:
print(cv.vocabulary_) # 사전

{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


In [28]:
list(cv.vocabulary_)

['you', 'know', 'want', 'your', 'love', 'like', 'what', 'should', 'do']

In [20]:
print(tfidfv.fit_transform(corpus).toarray())

[[0.         0.46735098 0.         0.46735098 0.         0.46735098
  0.         0.35543247 0.46735098]
 [0.         0.         0.79596054 0.         0.         0.
  0.         0.60534851 0.        ]
 [0.57735027 0.         0.         0.         0.57735027 0.
  0.57735027 0.         0.        ]]


In [21]:
print(tfidfv.vocabulary_)

{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


In [22]:
## transform 결과를 역으로 추출
cv.inverse_transform(cv.fit_transform(corpus).toarray())

[array(['know', 'love', 'want', 'you', 'your'], dtype='<U6'),
 array(['like', 'you'], dtype='<U6'),
 array(['do', 'should', 'what'], dtype='<U6')]

In [25]:
cv.get_feature_names() #단어만 확인

['do', 'know', 'like', 'love', 'should', 'want', 'what', 'you', 'your']

In [26]:
for i, value in enumerate(cv.get_feature_names()):
    print(i, ': ', value)

0 :  do
1 :  know
2 :  like
3 :  love
4 :  should
5 :  want
6 :  what
7 :  you
8 :  your


In [29]:
## 새로운 문장을 넣어서 어떤 단어들이 들어갔는지 판단해보자!
sentence = ['i like like smile want']

In [30]:
cv.transform(sentence).toarray()

array([[0, 0, 2, 0, 0, 1, 0, 0, 0]])

In [69]:
ham_dict = ['order', 'confirm', 'check', 'customer', 'payment', 'send', 'general', 'club']
spam_dict = ['advertise', 'promotion', 'sales', 'hu', 'special', 'sale', 'member', 'company']

In [70]:
cv1 = CountVectorizer()
tfidfv1 = TfidfVectorizer()

In [124]:
cv2 = CountVectorizer()
tfidfv2 = TfidfVectorizer()

In [125]:
cv1.fit(spam_dict)
tfidfv1.fit(spam_dict)

TfidfVectorizer()

In [126]:
cv1.vocabulary_

{'advertise': 0,
 'promotion': 4,
 'sales': 6,
 'hu': 2,
 'special': 7,
 'sale': 5,
 'member': 3,
 'company': 1}

In [127]:
tfidfv1.vocabulary_

{'advertise': 0,
 'promotion': 4,
 'sales': 6,
 'hu': 2,
 'special': 7,
 'sale': 5,
 'member': 3,
 'company': 1}

In [128]:
email = [" promotion !! hu good sales sale check payment"]

In [129]:
spam_cv = cv1.transform(email).toarray()
spam_tfidfv = tfidfv1.transform(email).toarray()
spam_cv

array([[0, 0, 1, 0, 1, 1, 1, 0]])

In [130]:
spam_tfidfv

array([[0. , 0. , 0.5, 0. , 0.5, 0.5, 0.5, 0. ]])

In [131]:
cv2.fit(ham_dict)
tfidfv2.fit(ham_dict)

TfidfVectorizer()

In [132]:
ham_cv = cv2.transform(email).toarray()
ham_tfidfv = tfidfv2.transform(email).toarray()
ham_cv

array([[1, 0, 0, 0, 0, 0, 1, 0]])

In [133]:
ham_tfidfv

array([[0.70710678, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.70710678, 0.        ]])

In [134]:
## result의 0이 아닌 개수의 합, ham의 0이 아닌 개수의 합
spam_count_cv = 0
spam_count_tfidfv = 0
ham_count_cv = 0
ham_count_tfidfv = 0

In [135]:
for item in spam_cv[0]:
    if (item!=0):
        spam_count_cv+=1
spam_count_cv

4

In [136]:
for item in spam_tfidfv[0]:
    if (item!=0):
        spam_count_tfidfv+=1
spam_count_tfidfv

4

In [137]:
for item in ham_cv[0]:
    if (item!=0):
        ham_count_cv+=1
ham_count_cv

2

In [138]:
for item in ham_tfidfv[0]:
    if (item!=0):
        ham_count_tfidfv+=1
ham_count_tfidfv

2

In [139]:
if spam_count_cv > ham_count_cv:
    print("spam email!")
else:
    print("ham email!!")


spam email!


In [140]:
if spam_count_tfidfv > ham_count_tfidfv:
    print("spam email!")
else:
    print("ham email!!")


spam email!


In [141]:
## 한글로 사전 만들어보시고, 다음을 스팸인지 아닌지 판단해보세요.
email2 = ['광고!! 허경영 good 세일 확인 지불']
spam_kor = ['광고', '허경영', '세일', '스팸', '특가']
ham_kor = ['환불', '영수증', '확인', '구매', '완료']

In [143]:
cv_kor= CountVectorizer()
tfidfv_kor = TfidfVectorizer()

In [238]:
def model_vectorizing(model1, model2, good, bad, sentence):
    model1.fit(good)
    good_model = model1.transform(sentence).toarray()
    
    model2.fit(bad)
    bad_model = model2.transform(sentence).toarray()
    count_bad=0
    count_good=0
    # print(good_model)
    # print(bad_model)
    # print(good_model)
    # print(bad_model)
    for item in good_model[0]:
        if (item!=0):
            count_good+=1
    for item in bad_model[0]:
        if (item!=0):
            count_bad+=1
    
    print("count_good:", count_good)
    print("count_bad:", count_bad)
    if count_good > count_bad:
        print("good!!")
    else:
        print("bad!!")

In [239]:
model_vectorizing(cv_kor,cv, ham_kor, spam_kor, email2)

count_good: 1
count_bad: 3
bad!!


In [240]:
model_vectorizing(tfidfv_kor,tfidfv, ham_kor, spam_kor, email2)

count_good: 1
count_bad: 3
bad!!


In [241]:
## 감정분류기를 만들어보세요.
## 긍정/부정 사전을 만들어보세요.
## input()을 이용해서 문장을 입력받으면, 긍정인지 부정인지 판단해보세요.
## tf-idf vectorizer를 사용하세요!!

In [242]:
tfidfv_good = TfidfVectorizer()
tfidfv_bad = TfidfVectorizer()
good = ['optimistic', 'success', 'benefit', 'significant', 'successful', 'encouraging', 'heartning', 'promising', 'bright', 'practical']
bad = ['tragic', 'pessimistic', 'horiffic', 'disaster', 'sad', 'discouraging', 'disheartning', 'unpromising', 'fail', 'failure']
emotional_phrase= "Son scores significant amount of goal for Tottenham Tottenham finishes a successful, promising, bright month"

In [248]:
def op_or_pes():
    sentence=[]
    sentence.append(input("sentence>>"))
    print("sentence:", sentence)
    model_vectorizing(tfidfv_good,tfidfv_bad, good, bad, sentence)

In [249]:
op_or_pes()

sentence>> Son scores significant amount of goal for Tottenham Tottenham finishes a successful, promising, bright month


sentence: ['Son scores significant amount of goal for Tottenham Tottenham finishes a successful, promising, bright month']
count_good: 4
count_bad: 0
good!!
